name: ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review

    # steps:
    #   - name: GenAI Code Review
    #     uses: cirolini/genai-code-review@v2
    #     with:
    #       openai_api_key: ${{ secrets.OPENAI_TOKEN }}
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       github_pr_id: ${{ github.event.number }}
    #       openai_model: "gpt-4o" 
    #       openai_temperature: 0.3 
    #       openai_max_tokens: 2048 
    #       mode: files 
    #       language: en 
    #     #   custom_prompt: "" 

    steps:
        - name: Checkout Repor
          uses: actions/checkout@v3

        - name: AI Code Reviewer
          uses: hohyon-ryu/ai-codereviewer@code_review
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
            OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
            OPENAI_API_MODEL: "gpt-4o" 
            exclude: "**/*.json, **/*.md" 
            language: "english" 