name: ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review

    steps:
      
    #   - name: Checkout Repo
    #     uses: actions/checkout@v3

    #   - name: AI Code Reviewer
    #     uses: hohyon-ryu/ai-codereviewer@code_review
    #     with:
    #       GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
    #       OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
    #       OPENAI_API_MODEL: "gpt-4o" # Optional: defaults to "gpt-4"
    #       exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas. defaults to  "**/*.json, **/*.md, yarn.lock, package-lock.json"
    #       language: "english" # Optional: defaults to "english"

          
        - name: Checkout Repor
          uses: actions/checkout@v3

        - name: OpenAI ChatGPT Code Review
          uses: manjunathsb100/chatgpt-code-review-action@1.0.7
          with:
            PROGRAMMING_LANGUAGE: 'Java'
            OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
            FULL_REVIEW_COMMENT: 'chatgpt'
            REVIEW_COMMENT_PREFIX: 'chatgpt:'