name: ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review

    steps:
      
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3

      # This step references the directory that contains the action.
      - uses: sshnaidm/gpt-code-review-action@v2.0
        with:
        #   github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          openai-key: ${{ secrets.OPENAI_TOKEN }}
          model: 'gpt-4o'
          # max-length: 8000
          prompt: 'Please explain what this code does (it is in Java but might contain some XML,JSON,YAML files too), and then perform a complete code review pointing improvement spots and potential bugs.'
          # post-if-error: false

    #   - name: Checkout Repo
    #     uses: actions/checkout@v3

    #   - name: AI Code Reviewer
    #     uses: hohyon-ryu/ai-codereviewer@code_review
    #     with:
    #       GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
    #       OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
    #       OPENAI_API_MODEL: "gpt-4o" # Optional: defaults to "gpt-4"
    #       exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas. defaults to  "**/*.json, **/*.md, yarn.lock, package-lock.json"
    #       language: "english" # Optional: defaults to "english"

          
    # steps:
    #     - name: Checkout Repor
    #       uses: actions/checkout@v3

    #     - name: OpenAI ChatGPT Code Review
    #       uses: manjunathsb100/chatgpt-code-review-action@1.0.7
    #       with:
    #         PROGRAMMING_LANGUAGE: 'JavaScript'
    #         OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
    #         GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
    #         FULL_REVIEW_COMMENT: 'chatgpt'
    #         REVIEW_COMMENT_PREFIX: 'chatgpt:'