name: ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review

    steps:
        - name: Checkout Repor
          uses: actions/checkout@v3

        - name: OpenAI ChatGPT Code Review
          uses: manjunathsb100/chatgpt-code-review-action@1.0.7
          with:
            PROGRAMMING_LANGUAGE: 'Java'
            OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
            FULL_REVIEW_COMMENT: 'chatgpt'
            REVIEW_COMMENT_PREFIX: 'chatgpt:'