name: ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review

    # steps:
    #   - name: GenAI Code Review
    #     uses: cirolini/genai-code-review@v2
    #     with:
    #       openai_api_key: ${{ secrets.OPENAI_TOKEN }}
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       github_pr_id: ${{ github.event.number }}
    #       openai_model: "gpt-4o" 
    #       openai_temperature: 0.3 
    #       openai_max_tokens: 2048 
    #       mode: files 
    #       language: en 
    #     #   custom_prompt: "" 

    steps:
      - name: OpenAI ChatGPT Code Review
        uses: adshao/chatgpt-code-review-action@v0.2.4
        with:
           PROGRAMMING_LANGUAGE: 'Java'
           REVIEW_COMMENT_PREFIX: 'chatgpt:'
           FULL_REVIEW_COMMENT: 'chatgpt'
           OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}