name: ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review

    steps:
      - name: Review Pull Request
        uses: JensAstrup/ai-reviewer@v1.0.2
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

    # steps:
    #     - name: Checkout Repor
    #       uses: actions/checkout@v3

    #     - name: OpenAI ChatGPT Code Review
    #       uses: manjunathsb100/chatgpt-code-review-action@1.0.7
    #       with:
    #         PROGRAMMING_LANGUAGE: 'JavaScript'
    #         OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
    #         GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
    #         FULL_REVIEW_COMMENT: 'chatgpt'
    #         REVIEW_COMMENT_PREFIX: 'chatgpt:'