name: ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review

    # steps:
    #   - name: GenAI Code Review
    #     uses: cirolini/genai-code-review@v2
    #     with:
    #       openai_api_key: ${{ secrets.OPENAI_TOKEN }}
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       github_pr_id: ${{ github.event.number }}
    #       openai_model: "gpt-4o" 
    #       openai_temperature: 0.3 
    #       openai_max_tokens: 2048 
    #       mode: files 
    #       language: en 
    #     #   custom_prompt: "" 

    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0 # needed to checkout all branches for the diff action to work

        # Check the PR diff using the current branch and the base branch of the PR
        - uses: GrantBirki/git-diff-action@v2.4.1
          id: git-diff-action
          with:
            json_diff_file_output: diff.json
            raw_diff_file_output: diff.txt
            file_output_only: "false"

        - name: OpenAI PR Review
          uses: koganei/llm-code-review@main
          id: review
          env:
            DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
          with:
            apiKey: ${{ secrets.OPENAI_TOKEN }}
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            githubRepository: ${{ github.repository }}
            githubPullRequestNumber: ${{ github.event.pull_request.number }}
            gitCommitHash: ${{ github.event.pull_request.head.sha }}
            temperature: "0.5"
            maxNewTokens: "2500"
            topK: "50"
            topP: "0.95"
            pullRequestDiff: |-
              $(cat $DIFF)
            pullRequestChunkSize: "7000"
            logLevel: "DEBUG"